create extension if not exists pgcrypto;

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  booking_time time not null,
  name text not null check (btrim(name) <> ''),
  phone text not null check (btrim(phone) <> ''),
  service text not null check (btrim(service) <> ''),
  review_token uuid not null default gen_random_uuid() unique,
  completed boolean not null default false,
  review_submitted boolean not null default false,
  created_at timestamptz not null default now(),
  unique (booking_date, booking_time)
);

alter table public.bookings enable row level security;

create or replace function public.reserve_booking(p_date date, p_time time, p_name text, p_phone text, p_service text)
returns uuid language plpgsql security definer set search_path = public as $$
declare new_token uuid;
begin
  if btrim(coalesce(p_name, '')) = '' or btrim(coalesce(p_phone, '')) = '' or btrim(coalesce(p_service, '')) = '' then return null; end if;
  insert into public.booking_slots (booking_date, booking_time, source) values (p_date, p_time, 'booked');
  insert into public.bookings (booking_date, booking_time, name, phone, service)
  values (p_date, p_time, btrim(p_name), btrim(p_phone), btrim(p_service)) returning review_token into new_token;
  return new_token;
exception when unique_violation then return null;
end;
$$;

create or replace function public.admin_bookings_for_date(p_date date, p_password text)
returns table(id bigint, booking_time time, name text, phone text, service text, completed boolean)
language sql security definer set search_path = public as $$
  select b.id, b.booking_time, b.name, b.phone, b.service, b.completed from public.bookings b
  where p_password = '0486' and b.booking_date = p_date order by b.booking_time;
$$;

create or replace function public.admin_complete_booking(p_booking_id bigint, p_password text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if p_password <> '0486' then return false; end if;
  update public.bookings set completed = true where id = p_booking_id;
  return found;
end;
$$;

create or replace function public.can_write_review(p_token uuid)
returns boolean language sql security definer set search_path = public as $$
  select exists(select 1 from public.bookings where review_token = p_token and completed and not review_submitted);
$$;

create or replace function public.submit_completed_review(p_token uuid, p_name text, p_region text, p_service text, p_content text)
returns boolean language plpgsql security definer set search_path = public as $$
declare booking_id bigint;
begin
  select id into booking_id from public.bookings where review_token = p_token and completed and not review_submitted for update;
  if booking_id is null then return false; end if;
  if btrim(coalesce(p_name,'')) = '' or btrim(coalesce(p_region,'')) = '' or btrim(coalesce(p_service,'')) = '' or btrim(coalesce(p_content,'')) = '' then return false; end if;
  insert into public.reviews (name, region, service, content) values (btrim(p_name), btrim(p_region), btrim(p_service), btrim(p_content));
  update public.bookings set review_submitted = true where id = booking_id;
  return true;
end;
$$;

grant execute on function public.reserve_booking(date,time,text,text,text) to anon, authenticated;
grant execute on function public.admin_bookings_for_date(date,text) to anon, authenticated;
grant execute on function public.admin_complete_booking(bigint,text) to anon, authenticated;
grant execute on function public.can_write_review(uuid) to anon, authenticated;
grant execute on function public.submit_completed_review(uuid,text,text,text,text) to anon, authenticated;
